"""Generate the DICT_5X5_1000 bit table and a test fixture from OpenCV.

Usage: pip install opencv-python-headless && python scripts/gen_dict.py
The table comes from the dictionary byte list; the fixture comes from rendered marker
images, so the frontend test checks our decoding against OpenCV's own rendering.
"""

import json
from pathlib import Path

import cv2
import numpy as np

SIZE = 5
OUT = Path(__file__).resolve().parent.parent / "src" / "aruco"
FIXTURE_IDS = [0, 1, 7, 42, 249, 250, 251, 500, 777, 999]

dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_5X5_1000)

codes = []
for marker_id in range(dictionary.bytesList.shape[0]):
    bits = cv2.aruco.Dictionary.getBitsFromByteList(dictionary.bytesList[marker_id : marker_id + 1], SIZE)
    value = 0
    for bit in bits.flatten():
        value = (value << 1) | int(bit)
    codes.append(f"{value:07x}")

(OUT / "dict5x5_1000.ts").write_text(
    "// Generated by scripts/gen_dict.py from OpenCV DICT_5X5_1000. Do not edit.\n"
    "// Each marker: 7 hex chars = 25 bits, row-major, MSB first, 1 = white cell.\n"
    f'export const DICT_5X5_1000 = "{"".join(codes)}";\n'
)

cells = SIZE + 2  # with the black border
fixture = {}
for marker_id in FIXTURE_IDS:
    image = cv2.aruco.generateImageMarker(dictionary, marker_id, cells * 10)
    grid = image[5::10, 5::10]  # sample the centre of every cell
    fixture[marker_id] = ["".join("1" if v > 127 else "0" for v in row) for row in (grid > 127) * 255]
(OUT / "fixture.json").write_text(json.dumps(fixture, indent=1) + "\n")
print(f"wrote {len(codes)} codes, fixture for {FIXTURE_IDS}")
