# Generated by Django 5.2.17 on 2026-09-25 02:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPin',
            fields=[
                ('role', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=8)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('x', models.FloatField(default=0.5)),
                ('y', models.FloatField(default=0.5)),
                ('enabled', models.BooleanField(default=True)),
                ('is_finish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_finish', 'number', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_finish', True)), fields=('is_finish',), name='single_finish_station')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'Телефон'), ('paper', 'Бумага')], max_length=5)),
                ('marker_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('prize_at', models.DateTimeField(blank=True, null=True)),
                ('prize_forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quest.station')),
            ],
            options={
                'ordering': ['marker_id'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quest.participant')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='scan', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='quest.participant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='quest.station')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'station'), name='unique_visit')],
            },
        ),
    ]
